---
settings:
  name: Upgrade Health Checker
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Actualizar la documentación de Health Checker
    url: "/index.html"
  - title: Notas de publicación
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Empezar
    entries:
    - title: Conoce Upgrade Health Checker
      url: "/learn-about-upgrade-health-checker.html"
    - title: Configura Upgrade Health Checker
      url: "/set-up-upgrade-health-checker.html"
  - title: Usa Upgrade Health Checker
    entries:
    - title: Genera un informe de actualización de ONTAP
      url: "/generate-report-upgrade-health-checker.html"
    - title: Automatiza la generación de informes
      url: "/automate-report-upgrade-health-checker.html"
  - title: Parámetros de entrada para Upgrade Health Checker
    url: "/upgrade-health-checker-input-parameters.html"
  - title: Preguntas frecuentes
    url: "/faq-upgrade-health-checker.html"
  - title: Avisos legales
    url: "/legal-notices.html"
