---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Puedes configurar correos electrónicos para recibir los informes de Upgrade Health Checker. 
---
= Recibe los informes de Upgrade Health Checker por correo electrónico
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puedes integrar correos electrónicos en Upgrade Health Checker para recibir informes en tu bandeja de entrada. Habilitas esta función a través del archivo config.yaml o un argumento de línea de comandos. Cuando está habilitada, Upgrade Health Checker envía los informes generados (HTML, Excel o JSON) a uno o más destinatarios configurados usando un servidor SMTP. Cuando la función está deshabilitada, no se envían informes. Si falla la generación de informes y el correo electrónico está habilitado, los archivos de registro se envían a los destinatarios configurados.



== Configurar mediante el archivo config.yaml

. Activa los informes por correo electrónico en el archivo config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Indica la configuración SMTP junto con los datos del remitente y el asunto:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Introduce las direcciones de correo electrónico de los destinatarios y configura qué formatos de informe se envían por correo electrónico, por ejemplo, HTML, EXCEL, JSON, ALL:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----




== Configurar mediante argumentos de línea de comandos

. Activar los informes por correo electrónico mediante argumentos de línea de comandos:
+
[listing]
----
./uhc --email-enabled=true
----
. Introduce las direcciones de correo electrónico de los destinatarios:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configura qué formatos de informe se envían por correo electrónico, por ejemplo, HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Los tres atributos siguientes se pueden configurar tanto mediante argumentos de línea de comandos como a través del archivo config.yaml; el resto de atributos solo se pueden configurar en el archivo config.yaml:

* Correo electrónico habilitado
* Destinatarios del correo electrónico
* Formatos de los informes por correo electrónico


Ten en cuenta que, cuando se proporcionan argumentos de línea de comandos, estos prevalecen sobre los valores del archivo config.yaml.

Por ejemplo:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====