---
sidebar: sidebar 
permalink: setup-email-upgrade-health-checker.html 
keywords: upgrade, health, checker 
summary: Puedes configurar correos electrónicos para recibir los informes de Upgrade Health Checker. 
---
= Recibe los informes de Upgrade Health Checker por correo electrónico
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Health Checker puede enviar informes directamente a tu bandeja de entrada. Activa esta función a través del archivo config.yaml o mediante un argumento de línea de comandos. Cuando está habilitado, Upgrade Health Checker envía los informes generados (HTML, Excel o JSON) a uno o varios destinatarios a través de un servidor SMTP. Cuando está deshabilitado, no se envía ningún informe. Si falla la generación de informes y el envío por correo electrónico está habilitado, Upgrade Health Checker envía los archivos de registro por correo electrónico a los destinatarios configurados.



[[configure-using-the-config-yaml-file]]
== Configurar mediante el archivo config.yaml

Puedes configurar los ajustes de correo electrónico en el archivo config.yaml activando los informes por correo electrónico, añadiendo los datos del servidor SMTP y especificando las direcciones de los destinatarios y los formatos de los informes.

. Activa los informes por correo electrónico en el archivo config.yaml.
+
[listing]
----
# Email Report Configuration
EMAIL:
  ENABLED: true
----
. Agrega la configuración de SMTP, los detalles del remitente y el asunto:
+
[listing]
----
# SMTP Server Configuration
EMAIL:
  ENABLED: true
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [<port-number>]
----
. Añade las direcciones de correo electrónico de los destinatarios y configura los formatos de informe que el sistema envía por correo electrónico, por ejemplo, HTML, EXCEL, JSON o ALL. También puedes usar autenticación y cifrado:
+
[listing]
----
# Recipient Email Addresses, report formats
EMAIL:
  ENABLED: true
  TO: <recipient>
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  RECIPIENTS: "user1@example.com, user2@example.com"
  REPORT_FORMATS: "HTML,EXCEL,JSON"   # valid values: HTML, EXCEL, JSON or ALL
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
    USE_SMTP_AUTH: true
    USE_TLS: true
    USE_SSL: true
    USERNAME: "user@example.com"
    PASSWORD: "********"
----




[[configure-using-command-line-arguments]]
== Configurar mediante argumentos de línea de comandos

Puedes configurar los ajustes básicos del correo electrónico mediante argumentos de línea de comandos para habilitar los informes, especificar los destinatarios y seleccionar los formatos de los informes.

. Activar los informes por correo electrónico mediante argumentos de línea de comandos:
+
[listing]
----
./uhc --email-enabled=true
----
. Introduce las direcciones de correo electrónico de los destinatarios:
+
[listing]
----
./uhc --email-recipients="user1@example.com, user2@example.com"
----
. Configura qué formatos de informe se envían por correo electrónico, por ejemplo, HTML, EXCEL, JSON:
+
[listing]
----
./uhc --email-report-formats=HTML,EXCEL,JSON
----


[NOTE]
====
Puedes configurar los tres atributos siguientes mediante argumentos de línea de comandos o el archivo config.yaml. Puedes configurar todos los atributos restantes solo en el archivo config.yaml:

* Correo electrónico habilitado
* Destinatarios del correo electrónico
* Formatos de los informes por correo electrónico


Ten en cuenta que los argumentos de la línea de comandos tienen prioridad sobre los valores del archivo config.yaml.

Por ejemplo:

[listing]
----
./uhc \
  --email-enabled=true
  --email-recipients="user1@example.com, user2@example.com" \
  --email-report-formats=HTML,EXCEL,JSON \
----
[listing]
----
EMAIL:
  FROM: "uhc-notify@example.com"
  SUBJECT: "UHC Upgrade Health Report"
  REPLY_TO: <email>
  SMTP:
    HOST: "smtp.example.com"
    PORT: [PORT]
----
====