---
sidebar: sidebar 
permalink: whats-new.html 
keywords: upgrade, health, checker, whats new, release, notes 
summary: Descubre qué hay de nuevo en este sitio doc. 
---
= Novedades en Upgrade Health Checker
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Descubre las novedades de Upgrade Health Checker (UHC). Puedes encontrar información adicional sobre mejoras navegando al mosaico de Upgrade Health Checker en el link:https://console.netapp.com/automationHub["Hub de Automatización de NetApp Console"^] y consultando los archivos de descarga más recientes de Upgrade Health Checker.



[[17-july-2026]]
== 17 de julio de 2026

Esta actualización añade varias mejoras, entre las que se incluyen un panel de control con vista general de los riesgos de la flota, compatibilidad con la autenticación y el cifrado del correo electrónico, informes sobre el recuento de unidades de disco, compatibilidad con la versión recomendada de ONTAP y comprobaciones IMT para NAS y SAN.

* Panel de control de UHC: ya está disponible la vista *Fleet Risk*
* Integración con el correo electrónico: compatibilidad con un servidor de correo electrónico con autenticación y cifrado
* Se añadió *Número de unidades* en el resumen del clúster en el informe
* Versión recomendada de ONTAP ahora compatible
* Se añadió compatibilidad con las comprobaciones IMT de NAS y SAN




[[11-june-2026]]
== 11 de junio de 2026

Esta actualización añade el envío de informes por correo electrónico, un parámetro del panel de control para obtener resúmenes rápidos del estado del sistema y nuevas secciones de documentación que te ayudarán a mantener y solucionar problemas de Upgrade Health Checker.

* UHC permite recibir los informes directamente en tu bandeja de entrada.
+
link:setup-email-upgrade-health-checker.html["Recibe los informes de Upgrade Health Checker por correo electrónico"].

* Introduce el parámetro  `--dashboard` que regenera el panel de control a partir de ejecuciones existentes en  `<runs>/dashboard/index.html` sin necesidad de conectarse a un clúster. Ofrece una visión a grandes rasgos del estado de salud de todos los clústeres a los que se ha accedido recientemente.
+
link:dashboard-upgrade-health-checker.html["Actualizar el panel de control de Health Checker"], link:upgrade-health-checker-input-parameters.html#dashboard["Parámetro del dashboard"].

* Se introduce una nueva sección de mantenimiento, solución de problemas y preguntas frecuentes.
+
** Realiza el mantenimiento de Upgrade Health Checker comprobando si hay actualizaciones, supervisando los registros en busca de problemas recurrentes y verificando que configuras la herramienta correctamente.
+
link:maintain-upgrade-health-checker.html["Mantén el verificador de estado de actualizaciones"].

** Soluciona los problemas habituales de Upgrade Health Checker y resuelve los errores que pueden impedir la planificación de la actualización de ONTAP.
+
link:troubleshoot-upgrade-health-checker.html["Soluciona problemas del verificador de estado de la actualización"].

** Preguntas frecuentes (FAQ) para Upgrade Health Checker.
+
link:faq-upgrade-health-checker.html["FAQ para Upgrade Health Checker"].







[[15-april-2026]]
== 15 abril 2026

Esta actualización añade un nuevo formato de informe XLSX y requiere acceso a un nuevo endpoint para que funcionen las actualizaciones automáticas.

* Debes conceder a UHC acceso a un nuevo endpoint (+https://api.activeiq.netapp.com+) para que funcionen las funciones de actualización automática.
+
link:set-up-upgrade-health-checker.html["Descarga y configura Upgrade Health Checker"].

* UHC ahora ofrece un nuevo formato de informe (.XLSX - human-editable) que complementa los formatos HTML (human-readable) y JSON (machine-readable).
+
link:generate-report-upgrade-health-checker.html["Genera un informe de actualización de ONTAP"].

+
link:automate-report-upgrade-health-checker.html["Automatiza la generación de planes de actualización con Upgrade Health Checker"].





[[13-february-2026]]
== 13 febrero 2026

Ya está disponible Upgrade Health Checker. Esta herramienta genera informes detallados in situ para ayudarte a completar con éxito una actualización de ONTAP. Puedes usar Upgrade Health Checker con los marcos de automatización y orquestación existentes para ahorrar tiempo al actualizar uno o varios clústeres. Upgrade Health Checker admite actualizaciones a ONTAP 9.11.1 y versiones posteriores.

link:learn-about-upgrade-health-checker.html["Conoce más sobre Upgrade Health Checker"].
